
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

  host: localhost
  port: 5432


development:
  <<: *defaults
  database: online-personal-order-development


test:
  <<: *defaults
  database: online-personal-order-test

production:
  <<: *defaults
  database: online-personal-order-production
